export enum SocketEvent {
  NEW_MESSAGE = "NEW_MESSAGE",
  TYPING = "TYPING",
  STOP_TYPING = "STOP_TYPING",
  READ_RECEIPT = "READ_RECEIPT",
  USER_ONLINE = "USER_ONLINE",
  USER_OFFLINE = "USER_OFFINE",
  DELETE_MESSAGE = "DELETE_MESSAGE",
  EDIT_MESSAGE = "EDIT_MESSAGE",
  MESSAGE_REACTION = "MESSAGE_REACTION",
  
}

export enum MessageType {
  TEXT = "TEXT",
  IMAGE = "IMAGE",
  AUDIO = "AUDIO",
  VIDEO = "VIDEO",
  FILE = "FILE",
  LOCATION = "LOCATION",
}
