export enum SocketEvent {
  NEW_MESSAGE = "NEW_MESSAGE",
  TYPING = "TYPING",
  STOP_TYPING = "STOP_TYPING",
  READ_RECEIPT = "READ_RECEIPT",
  USER_ONLINE = "USER_ONLINE",
  USER_OFFLINE = "USER_OFFINE",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  MESSAGE_EDITED = "MESSAGE_EDITED",
}

export enum MessageType {
  TEXT = "TEXT",
  IMAGE = "IMAGE",
  AUDIO = "AUDIO",
  VIDEO = "VIDEO",
  FILE = "FILE",
  LOCATION = "LOCATION",
}
